# Ravedude.toml
[general]
open-console = true
serial-baudrate = 57600
board = "uno"

# For documentation about this file, check here:
# https://github.com/Rahix/avr-hal/blob/main/ravedude/README.md#ravedudetoml-format