[wokwi]
version=1
#firmware='target/avr-none/debug/rust-x-arduino.elf'
#elf='target/avr-none/debug/rust-x-arduino.elf'
#
firmware='target/avr-none/release/rust-x-arduino.elf'
elf='target/avr-none/release/rust-x-arduino.elf'